### ISSUE TITLE
Add screenshots to the README.md

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uado#47]
Howdy Folks,

When this is ready can you please add screenshots to the README?

Thanks!

**Comment by vincentcastagna** [comment]
Hey @ghuntley,

I'll do that. 5 screenshots for the five main pages is ok ?

**Comment by vincentcastagna** [comment]
![uado_organizations](https://user-images.githubusercontent.com/15191066/60998739-8e6beb00-a327-11e9-9c00-3a45afcdd05b.png)
![uado_profile](https://user-images.githubusercontent.com/15191066/60998740-8e6beb00-a327-11e9-89fb-2ef80ade7b63.png)
![uado_projectdetail](https://user-images.githubusercontent.com/15191066/60998742-8e6beb00-a327-11e9-9b04-7deb29d9525a.png)
![uado_projects](https://user-images.githubusercontent.com/15191066/60998743-8e6beb00-a327-11e9-8ee8-783d9a6be5f3.png)
![uado_task](https://user-images.githubusercontent.com/15191066/60998744-8e6beb00-a327-11e9-96d0-b942119aa87c.png)
![uado_workitem](https://user-images.githubusercontent.com/15191066/60998746-8e6beb00-a327-11e9-81e5-bc3ec7a13a70.png)

**Comment by vincentcastagna** [comment]
![uado_projectdetail](https://user-images.githubusercontent.com/15191066/61002038-c32f7080-a32e-11e9-9912-a6d8bebd37ae.png)
![uado_projects](https://user-images.githubusercontent.com/15191066/61002039-c32f7080-a32e-11e9-9a8c-35250a6a1674.png)
![uado_task](https://user-images.githubusercontent.com/15191066/61002040-c32f7080-a32e-11e9-8e0a-387886207fe2.png)
![uado_workitem](https://user-images.githubusercontent.com/15191066/61002041-c3c80700-a32e-11e9-8e69-778f01d515a2.png)
![uado_organizations](https://user-images.githubusercontent.com/15191066/61002042-c3c80700-a32e-11e9-9a38-69e5ebfbdf04.png)
![uado_profile](https://user-images.githubusercontent.com/15191066/61002043-c3c80700-a32e-11e9-8504-51adaec50ba4.png)

**Comment by vincentcastagna** [comment]
We need to update screenshots to be up to date with latest releases

**Comment by bh6erk** [comment]
Hi @vincentcastagna ,
I am on it.
